version: '3.8'

volumes:
  pg-data:

services:
  postgres:
    image: us-docker.pkg.dev/easyship-production/external/postgres:17-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=root
      - POSTGRES_DB=good_night_api_development
      - TZ=UTC
      - PGTZ=UTC
    volumes:
      - ./dump-files:/dump-files
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  good-night-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgresql://root@postgres:5432/good_night_api_development
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
    command:
      - sh
      - -c
      - |
        bundle install;
        bundle exec rake db:create db:migrate;
        bundle exec rails server -p 80 -b '0.0.0.0';
    ports:
      - "3003:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/rails:cached
      - ./storage:/rails/storage
      - ./log:/rails/log
