default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: good_night_api_development

test:
  <<: *default
  database: good_night_api_test

production:
  primary: &primary_production
    <<: *default
    database: good_night_api_production
    username: good_night_api
    password: <%= ENV["GOOD_NIGHT_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: good_night_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: good_night_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: good_night_api_production_cable
    migrations_paths: db/cable_migrate
